name: Release
on:
  release:
    types: [published]

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          NEW_IMAGE_VERSION: ${GITHUB_REF/refs\/tags\//}
        with:
          push: true
          tags: |
            leocode/image-service:latest
            leocode/image-service:${GITHUB_REF/refs\/tags\//}
